const countryOptions = [
    { value: "0.175", label: "Albania" },
    { value: "0.308", label: "Argentina" },
    { value: "0.209", label: "Armenia" },
    { value: "1.192", label: "Australia" },
    { value: "0.842", label: "Austria" },
    { value: "0.309", label: "Azerbaijan" },
    { value: "1.167", label: "Bahrain" },
    { value: "0.067", label: "Bangladesh" },
    { value: "0.542", label: "Belarus" },
    { value: "1.450", label: "Belgium" },
    { value: "0.050", label: "Benin" },
    { value: "0.167", label: "Bolivia" },
    { value: "0.417", label: "Botswana" },
    { value: "0.192", label: "Brazil" },
    { value: "1.875", label: "Brunei Darussalam" },
    { value: "0.467", label: "Bulgaria" },
    { value: "0.025", label: "Burkina Faso" },
    { value: "0.202", label: "Cambodia" },
    { value: "0.033", label: "Cameroon" },
    { value: "1.176", label: "Canada" },
    { value: "0.426", label: "Chile" },
    { value: "0.583", label: "China" },
    { value: "0.201", label: "Colombia" },
    { value: "0.208", label: "Costa Rica" },
    { value: "0.475", label: "Croatia" },
    { value: "0.525", label: "Cyprus" },
    { value: "0.867", label: "Czech Republic" },
    { value: "0.050", label: "Côte d'Ivoire" },
    { value: "0.667", label: "Denmark" },
    { value: "0.225", label: "Dominican Republic" },
    { value: "0.201", label: "Ecuador" },
    { value: "0.200", label: "Egypt" },
    { value: "0.125", label: "El Salvador" },
    { value: "0.925", label: "Estonia" },
    { value: "0.017", label: "Ethiopia" },
    { value: "0.801", label: "Finland" },
    { value: "0.542", label: "France" },
    { value: "0.267", label: "Georgia" },
    { value: "0.843", label: "Germany" },
    { value: "0.058", label: "Ghana" },
    { value: "0.417", label: "Greece" },
    { value: "0.117", label: "Guatemala" },
    { value: "0.042", label: "Guinea" },
    { value: "0.075", label: "Honduras" },
    { value: "0.942", label: "Hong Kong" },
    { value: "0.558", label: "Hungary" },
    { value: "0.150", label: "India" },
    { value: "0.218", label: "Indonesia" },
    { value: "0.608", label: "Iran" },
    { value: "0.850", label: "Ireland" },
    { value: "0.775", label: "Israel" },
    { value: "0.608", label: "Italy" },
    { value: "0.217", label: "Jamaica" },
    { value: "0.825", label: "Japan" },
    { value: "0.242", label: "Jordan" },
    { value: "0.767", label: "Kazakhstan" },
    { value: "0.050", label: "Kenya" },
    { value: "1.933", label: "Kuwait" },
    { value: "0.233", label: "Kyrgyzstan" },
    { value: "0.258", label: "Laos" },
    { value: "0.675", label: "Latvia" },
    { value: "0.642", label: "Lithuania" },
    { value: "1.250", label: "Luxembourg" },
    { value: "0.017", label: "Madagascar" },
    { value: "0.008", label: "Malawi" },
    { value: "0.633", label: "Malaysia" },
    { value: "1.633", label: "Malta" },
    { value: "0.383", label: "Mauritius" },
    { value: "0.342", label: "Mexico" },
    { value: "1.083", label: "Mongolia" },
    { value: "0.158", label: "Morocco" },
    { value: "0.042", label: "Mozambique" },
    { value: "0.325", label: "Namibia" },
    { value: "0.075", label: "Nepal" },
    { value: "0.800", label: "Netherlands" },
    { value: "0.667", label: "New Zealand" },
    { value: "0.083", label: "Nicaragua" },
    { value: "0.050", label: "Nigeria" },
    { value: "0.767", label: "Norway" },
    { value: "1.008", label: "Oman" },
    { value: "0.083", label: "Pakistan" },
    { value: "0.350", label: "Panama" },
    { value: "0.158", label: "Paraguay" },
    { value: "0.167", label: "Peru" },
    { value: "0.133", label: "Philippines" },
    { value: "0.675", label: "Poland" },
    { value: "0.425", label: "Portugal" },
    { value: "2.192", label: "Qatar" },
    { value: "0.367", label: "Romania" },
    { value: "0.792", label: "Russian Federation" },
    { value: "0.017", label: "Rwanda" },
    { value: "1.483", label: "Saudi Arabia" },
    { value: "0.083", label: "Senegal" },
    { value: "2.275", label: "Singapore" },
    { value: "0.617", label: "Slovakia" },
    { value: "0.808", label: "Slovenia" },
    { value: "0.475", label: "South Africa" },
    { value: "1.142", label: "South Korea" },
    { value: "0.500", label: "Spain" },
    { value: "0.142", label: "Sri Lanka" },
    { value: "0.558", label: "Sweden" },
    { value: "1.177", label: "Switzerland" },
    { value: "1.017", label: "Taiwan" },
    { value: "0.125", label: "Tajikistan" },
    { value: "0.025", label: "Tanzania" },
    { value: "0.325", label: "Thailand" },
    { value: "1.425", label: "Trinidad and Tobago" },
    { value: "0.192", label: "Tunisia" },
    { value: "0.392", label: "Turkey" },
    { value: "0.017", label: "Uganda" },
    { value: "0.392", label: "Ukraine" },
    { value: "1.783", label: "United Arab Emirates" },
    { value: "0.642", label: "United Kingdom" },
    { value: "1.417", label: "United States of America" },
    { value: "0.258", label: "Uruguay" },
    { value: "0.018", label: "Venezuela" },
    { value: "0.183", label: "Vietnam" },
    { value: "0.042", label: "Zambia" },
    { value: "0.067", label: "Zimbabwe" }
];

export default countryOptions;
